old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            read_write_timeout: 4
    producers:
      messaging:
        class: App\Service\Rabbit\MessagingProducer
        connection:       default
        exchange_options: { name: 'jira', type: direct }
    consumers:
      messaging:
        connection:       default
        exchange_options: { name: 'jira', type: direct }
        queue_options:    { name: 'jira'}
        callback:         message_service
        enable_logger:    true
